// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu/index.vue')['default']
    Rotation: typeof import('./src/components/Rotation/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrollbar: typeof import('./src/components/Scrollbar/index.vue')['default']
  }
}
