// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddCollectModel: typeof import('./src/components/AddCollectModel/index.vue')['default']
    AnotherArticle: typeof import('./src/components/AnotherArticle/index.vue')['default']
    Barrage: typeof import('./src/components/Barrage/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    Carousel: typeof import('./src/components/Carousel/index.vue')['default']
    CollectModel: typeof import('./src/components/CollectModel/index.vue')['default']
    Comment: typeof import('./src/components/Comment/index.vue')['default']
    ContentMenu: typeof import('./src/components/ContentMenu/index.vue')['default']
    DraftInput: typeof import('./src/components/DraftInput/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    Emoji: typeof import('./src/components/Emoji/index.vue')['default']
    Empty: typeof import('./src/components/Empty/index.vue')['default']
    ExitReminder: typeof import('./src/components/ExitReminder/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Image: typeof import('./src/components/Image/index.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu/index.vue')['default']
    LineCard: typeof import('./src/components/LineCard/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MackdownEditor: typeof import('./src/components/MackdownEditor/index.vue')['default']
    Messages: typeof import('./src/components/Messages/index.vue')['default']
    Multibar: typeof import('./src/components/Multibar/index.vue')['default']
    Preview: typeof import('./src/components/Preview/index.vue')['default']
    PreviewHeader: typeof import('./src/components/PreviewHeader/index.vue')['default']
    Qrcode: typeof import('./src/components/Qrcode/index.vue')['default']
    Reel: typeof import('./src/components/Reel/index.vue')['default']
    ResetForm: typeof import('./src/components/ResetForm/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./src/components/Timeline/index.vue')['default']
    Toc: typeof import('./src/components/Toc/index.vue')['default']
    ToTopIcon: typeof import('./src/components/ToTopIcon/index.vue')['default']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
    WordCloud: typeof import('./src/components/WordCloud/index.vue')['default']
  }
}
